
package ma.m2m.gateway.lydec;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-11-27T20:38:58.833+01:00
 * Generated source version: 3.4.5
 *
 */
public final class GererEncaissement_GererEncaissement_Client {

    private static final QName SERVICE_NAME = new QName("http://service.lydec.com", "GererEncaissementService");

    private GererEncaissement_GererEncaissement_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GererEncaissementService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GererEncaissementService ss = new GererEncaissementService(wsdlURL, SERVICE_NAME);
        GererEncaissement port = ss.getGererEncaissement();

        {
        System.out.println("Invoking ecrireSignature...");
        ma.m2m.gateway.lydec.SignatureComplete _ecrireSignature_pSignatureComplete = null;
        ma.m2m.gateway.lydec.ReponseSignature _ecrireSignature__return = port.ecrireSignature(_ecrireSignature_pSignatureComplete);
        System.out.println("ecrireSignature.result=" + _ecrireSignature__return);


        }
        {
        System.out.println("Invoking ecrireSignatureParTransaction...");
        ma.m2m.gateway.lydec.SignaturesParTransaction _ecrireSignatureParTransaction_pSignaturesParTransaction = null;
        ma.m2m.gateway.lydec.ReponseSignatureParTransaction _ecrireSignatureParTransaction__return = port.ecrireSignatureParTransaction(_ecrireSignatureParTransaction_pSignaturesParTransaction);
        System.out.println("ecrireSignatureParTransaction.result=" + _ecrireSignatureParTransaction__return);


        }
        {
        System.out.println("Invoking lireImpayes...");
        java.lang.String _lireImpayes_pCritere = "";
        int _lireImpayes_pTypeCritere = 0;
        java.lang.String _lireImpayes_pNom = "";
        int _lireImpayes_pAgence = 0;
        ma.m2m.gateway.lydec.Impayes _lireImpayes__return = port.lireImpayes(_lireImpayes_pCritere, _lireImpayes_pTypeCritere, _lireImpayes_pNom, _lireImpayes_pAgence);
        System.out.println("lireImpayes.result=" + _lireImpayes__return);


        }
        {
        System.out.println("Invoking ecrireReglements...");
        ma.m2m.gateway.lydec.DemandesReglements _ecrireReglements_pDemandeReglements = null;
        ma.m2m.gateway.lydec.ReponseReglements _ecrireReglements__return = port.ecrireReglements(_ecrireReglements_pDemandeReglements);
        System.out.println("ecrireReglements.result=" + _ecrireReglements__return);


        }
        {
        System.out.println("Invoking ecrireReglementsParLot...");
        ma.m2m.gateway.lydec.DemandesReglementsParLot _ecrireReglementsParLot_pDemandeReglementsParLot = null;
        ma.m2m.gateway.lydec.ReponseReglementsParLot _ecrireReglementsParLot__return = port.ecrireReglementsParLot(_ecrireReglementsParLot_pDemandeReglementsParLot);
        System.out.println("ecrireReglementsParLot.result=" + _ecrireReglementsParLot__return);


        }
        {
        System.out.println("Invoking ecrireSignatureParPointEnc...");
        ma.m2m.gateway.lydec.SignaturesParPointEnc _ecrireSignatureParPointEnc_pSignaturesParPointEnc = null;
        ma.m2m.gateway.lydec.ReponseSignatureParPointEnc _ecrireSignatureParPointEnc__return = port.ecrireSignatureParPointEnc(_ecrireSignatureParPointEnc_pSignaturesParPointEnc);
        System.out.println("ecrireSignatureParPointEnc.result=" + _ecrireSignatureParPointEnc__return);


        }

        System.exit(0);
    }

}
