package ma.m2m.gateway.lydec;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-11-27T20:38:58.906+01:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://service.lydec.com", name = "GererEncaissement")
@XmlSeeAlso({ObjectFactory.class})
public interface GererEncaissement {

    @WebMethod
    @RequestWrapper(localName = "ecrireSignature", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireSignature")
    @ResponseWrapper(localName = "ecrireSignatureResponse", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireSignatureResponse")
    @WebResult(name = "ecrireSignatureReturn", targetNamespace = "http://service.lydec.com")
    public ma.m2m.gateway.lydec.ReponseSignature ecrireSignature(

        @WebParam(name = "pSignatureComplete", targetNamespace = "http://service.lydec.com")
        ma.m2m.gateway.lydec.SignatureComplete pSignatureComplete
    );

    @WebMethod
    @RequestWrapper(localName = "ecrireSignatureParTransaction", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireSignatureParTransaction")
    @ResponseWrapper(localName = "ecrireSignatureParTransactionResponse", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireSignatureParTransactionResponse")
    @WebResult(name = "ecrireSignatureParTransactionReturn", targetNamespace = "http://service.lydec.com")
    public ma.m2m.gateway.lydec.ReponseSignatureParTransaction ecrireSignatureParTransaction(

        @WebParam(name = "pSignaturesParTransaction", targetNamespace = "http://service.lydec.com")
        ma.m2m.gateway.lydec.SignaturesParTransaction pSignaturesParTransaction
    );

    @WebMethod
    @RequestWrapper(localName = "lireImpayes", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.LireImpayes")
    @ResponseWrapper(localName = "lireImpayesResponse", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.LireImpayesResponse")
    @WebResult(name = "lireImpayesReturn", targetNamespace = "http://service.lydec.com")
    public ma.m2m.gateway.lydec.Impayes lireImpayes(

        @WebParam(name = "pCritere", targetNamespace = "http://service.lydec.com")
        java.lang.String pCritere,
        @WebParam(name = "pTypeCritere", targetNamespace = "http://service.lydec.com")
        int pTypeCritere,
        @WebParam(name = "pNom", targetNamespace = "http://service.lydec.com")
        java.lang.String pNom,
        @WebParam(name = "pAgence", targetNamespace = "http://service.lydec.com")
        int pAgence
    );

    @WebMethod
    @RequestWrapper(localName = "ecrireReglements", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireReglements")
    @ResponseWrapper(localName = "ecrireReglementsResponse", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireReglementsResponse")
    @WebResult(name = "ecrireReglementsReturn", targetNamespace = "http://service.lydec.com")
    public ma.m2m.gateway.lydec.ReponseReglements ecrireReglements(

        @WebParam(name = "pDemandeReglements", targetNamespace = "http://service.lydec.com")
        ma.m2m.gateway.lydec.DemandesReglements pDemandeReglements
    );

    @WebMethod
    @RequestWrapper(localName = "ecrireReglementsParLot", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireReglementsParLot")
    @ResponseWrapper(localName = "ecrireReglementsParLotResponse", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireReglementsParLotResponse")
    @WebResult(name = "ecrireReglementsParLotReturn", targetNamespace = "http://service.lydec.com")
    public ma.m2m.gateway.lydec.ReponseReglementsParLot ecrireReglementsParLot(

        @WebParam(name = "pDemandeReglementsParLot", targetNamespace = "http://service.lydec.com")
        ma.m2m.gateway.lydec.DemandesReglementsParLot pDemandeReglementsParLot
    );

    @WebMethod
    @RequestWrapper(localName = "ecrireSignatureParPointEnc", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireSignatureParPointEnc")
    @ResponseWrapper(localName = "ecrireSignatureParPointEncResponse", targetNamespace = "http://service.lydec.com", className = "ma.m2m.gateway.lydec.EcrireSignatureParPointEncResponse")
    @WebResult(name = "ecrireSignatureParPointEncReturn", targetNamespace = "http://service.lydec.com")
    public ma.m2m.gateway.lydec.ReponseSignatureParPointEnc ecrireSignatureParPointEnc(

        @WebParam(name = "pSignaturesParPointEnc", targetNamespace = "http://service.lydec.com")
        ma.m2m.gateway.lydec.SignaturesParPointEnc pSignaturesParPointEnc
    );
}
