package ma.m2m.gateway.lydec;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2023-11-27T20:38:58.921+01:00
 * Generated source version: 3.4.5
 * wsdlLocation = "file:/D:/Projets-Ecommerce/GW_PAIEMENT_API/Sources/GW_PAIEMENT/src/main/resources/wsdl/GererEncaissement.wsdl",
 */
@WebServiceClient(name = "GererEncaissementService",
                  wsdlLocation = "http://192.168.20.33:80/lydecWebServices/services/GererEncaissement?wsdl",
                  targetNamespace = "http://service.lydec.com")
public class GererEncaissementService extends Service {

    //public final static URL WSDL_LOCATION;
    public static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.lydec.com", "GererEncaissementService");
    public final static QName GererEncaissement = new QName("http://service.lydec.com", "GererEncaissement");
    static {
        /*URL url = null;
        try {
            url = new URL("http://192.168.20.33:80/lydecWebServices/services/GererEncaissement?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GererEncaissementService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://192.168.20.33:80/lydecWebServices/services/GererEncaissement?wsdl");
        }
        WSDL_LOCATION = url;*/
    }

    public GererEncaissementService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GererEncaissementService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
        WSDL_LOCATION = wsdlLocation;
    }

    public GererEncaissementService() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns GererEncaissement
     */
    @WebEndpoint(name = "GererEncaissement")
    public GererEncaissement getGererEncaissement() {
        return super.getPort(GererEncaissement, GererEncaissement.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GererEncaissement
     */
    @WebEndpoint(name = "GererEncaissement")
    public GererEncaissement getGererEncaissement(WebServiceFeature... features) {
        return super.getPort(GererEncaissement, GererEncaissement.class, features);
    }

}
